version: "3.1"

services:

  fledge-power:
    container_name: fledge
    image: fledgepower/fledge
    build:
      context: fledge/
      dockerfile: fledge.dockerfile
    ports:
      - "8081:8081"
      - "1995:1995"
      - "6683:6683"
      - "2404:2404"
      # - "443:443"

    networks:
      - fledge-power

  fledge-gui:
    container_name: fledge-gui
    image: fledgepower/fledge-gui
    build:
      context: fledge-gui/
      dockerfile: fledge-gui.dockerfile
    ports:
      - "8080:80"
      # - "443:443"

    networks:
      - fledge-power

networks:
  fledge-power:
    driver: bridge
